openapi: 3.0.3

info:
  title: Social Network API
  description: Current API describes interaction with Social Network
  version: 1.0.0

tags:
  - name: SocialNetworkAPI
  - name: Analytics

paths:
  /posts:
    post:
      summary: Create post
      description: Method creates posts
      tags:
        - SocialNetworkAPI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descr:
                  type: string
                  description: descr
              required:
                - descr
            examples:
              request:
                value:
                  descr: "Beautiful place"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: string
                    description: id of created post
                required:
                  - post_id
              examples:
                response:
                  value:
                    post_id: "834ef368-e04c-4ac7-8f20-2e2814b0bfdc"
        400:
          description: Bad Request
        500:
          description: Server error
  /posts/{post_id}:
    get:
      summary: Get post by id
      description: Method gets post by id
      tags:
        - SocialNetworkAPI
      parameters:
        - name: post_id
          in: path
          required: true
          description: Post id
          schema:
            type : string
      responses:
        200:
          description: Ok
        404:
          description: Not found
        500:
          description: Server error
  /posts/{post_id}/react:
    post:
      summary: Add reaction on post
      description: Method adds reactions on post
      tags:
        - SocialNetworkAPI
      parameters:
        - name: post_id
          in: path
          required: true
          description: Post id
          schema:
            type : string
      responses:
        200:
          description: Ok
        404:
          description: Not found
        500:
          description: Server error

  /posts/{user_id}/subscribe:
    post:
      summary: Subscribe on user
      description: Method allows subscription on user
      tags:
        - SocialNetworkAPI
      parameters:
        - name: user_id
          in: path
          required: true
          description: User id
          schema:
            type : string
      responses:
        200:
          description: Ok
        404:
          description: Not found
        500:
          description: Server error

  /posts/{post_id}/comments:
    post:
      summary: Leave comment
      description: Method leaves comments
      tags:
        - SocialNetworkAPI
      parameters:
        - name: post_id
          in: path
          required: true
          description: Post id
          schema:
            type : string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descr:
                  type: string
                  description: descr
              required:
                - descr
            examples:
              request:
                value:
                  descr: "Test comment"
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        404:
          description: Not found
        500:
          description: Server error


  /find_places: # Надо сюда добавить какой-то параметр, погуглить
    get:
      summary: Find popular places
      description: Method finds popular places
      tags:
        - SocialNetworkAPI
      responses:
        200:
          description: Ok
        500:
          description: Server error

  /feed:
    get:
      summary: Update feed
      description: Method updates feed
      tags:
        - SocialNetworkAPI
      responses:
        200:
          description: Ok
        500:
          description: Server error
